In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
data = pd.read_csv('baseball.csv')

In [14]:
data.head(50)

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424
5,CHW,AL,2012,748,676,85,0.318,0.422,0.255,0,NaN,NaN,162,0.319,0.405
6,CIN,NL,2012,669,588,97,0.315,0.411,0.251,1,2.0,4.0,162,0.305,0.390
7,CLE,AL,2012,667,845,68,0.324,0.381,0.251,0,NaN,NaN,162,0.336,0.430
8,COL,NL,2012,758,890,64,0.330,0.436,0.274,0,NaN,NaN,162,0.357,0.470
9,DET,AL,2012,726,670,88,0.335,0.422,0.268,1,6.0,2.0,162,0.314,0.402
10,HOU,NL,2012,583,794,55,0.302,0.371,0.236,0,NaN,NaN,162,0.337,0.427
11,KCR,AL,2012,676,746,72,0.317,0.400,0.265,0,NaN,NaN,162,0.339,0.423
12,LAA,AL,2012,767,699,89,0.332,0.433,0.274,0,NaN,NaN,162,0.310,0.403
13,LAD,NL,2012,637,597,86,0.317,0.374,0.252,0,NaN,NaN,162,0.310,0.364
14,MIA,NL,2012,609,724,69,0.308,0.382,0.244,0,NaN,NaN,162,0.327,0.399
15,MIL,NL,2012,776,733,83,0.325,0.437,0.259,0,NaN,NaN,162,0.326,0.414
16,MIN,AL,2012,701,832,66,0.325,0.390,0.260,0,NaN,NaN,162,0.333,0.442
17,NYM,NL,2012,650,709,74,0.316,0.386,0.249,0,NaN,NaN,162,0.315,0.401
18,NYY,AL,2012,804,668,95,0.337,0.453,0.265,1,3.0,3.0,162,0.311,0.419
19,OAK,AL,2012,713,614,94,0.310,0.404,0.238,1,4.0,4.0,162,0.306,0.378
20,PHI,NL,2012,684,680,81,0.317,0.400,0.255,0,NaN,NaN,162,0.306,0.407
21,PIT,NL,2012,651,674,79,0.304,0.395,0.243,0,NaN,NaN,162,0.314,0.390
22,SDP,NL,2012,651,710,76,0.319,0.380,0.247,0,NaN,NaN,162,0.319,0.398
23,SEA,AL,2012,619,651,75,0.296,0.369,0.234,0,NaN,NaN,162,0.308,0.394
24,SFG,NL,2012,718,649,94,0.327,0.397,0.269,1,4.0,1.0,162,0.313,0.393
25,STL,NL,2012,765,648,88,0.338,0.421,0.271,1,6.0,3.0,162,0.313,0.387
26,TBR,AL,2012,697,577,90,0.317,0.394,0.240,0,NaN,NaN,162,0.294,0.352
27,TEX,AL,2012,808,707,93,0.334,0.446,0.273,1,5.0,5.0,162,0.309,0.408
28,TOR,AL,2012,716,784,73,0.309,0.407,0.245,0,NaN,NaN,162,0.335,0.438
29,WSN,NL,2012,731,594,98,0.322,0.428,0.261,1,1.0,4.0,162,0.303,0.373
30,ARI,NL,2011,731,662,94,0.322,0.413,0.250,1,5.0,4.0,162,0.316,0.409
31,ATL,NL,2011,641,605,89,0.308,0.387,0.243,0,NaN,NaN,162,0.310,0.361
32,BAL,AL,2011,708,860,69,0.316,0.413,0.257,0,NaN,NaN,162,0.341,0.460
33,BOS,AL,2011,875,737,90,0.349,0.461,0.280,0,NaN,NaN,162,0.322,0.392
34,CHC,NL,2011,654,756,71,0.314,0.401,0.256,0,NaN,NaN,162,0.335,0.413
35,CHW,AL,2011,654,706,79,0.319,0.388,0.252,0,NaN,NaN,162,0.317,0.397
36,CIN,NL,2011,735,720,79,0.326,0.408,0.256,0,NaN,NaN,162,0.325,0.415
37,CLE,AL,2011,704,760,80,0.317,0.396,0.250,0,NaN,NaN,162,0.323,0.413
38,COL,NL,2011,735,774,73,0.329,0.410,0.258,0,NaN,NaN,162,0.331,0.431
39,DET,AL,2011,787,711,95,0.340,0.434,0.277,1,4.0,3.0,162,0.321,0.396
40,FLA,NL,2011,625,702,72,0.318,0.388,0.247,0,NaN,NaN,162,0.316,0.401
41,HOU,NL,2011,615,796,56,0.311,0.374,0.258,0,NaN,NaN,162,0.337,0.432
42,KCR,AL,2011,730,762,71,0.329,0.415,0.275,0,NaN,NaN,162,0.337,0.425
43,LAA,AL,2011,667,633,86,0.313,0.402,0.253,0,NaN,NaN,162,0.313,0.388
44,LAD,NL,2011,644,612,82,0.322,0.375,0.257,0,NaN,NaN,161,0.310,0.371
45,MIL,NL,2011,721,638,96,0.325,0.425,0.261,1,3.0,3.0,162,0.304,0.385
46,MIN,AL,2011,619,804,63,0.306,0.360,0.247,0,NaN,NaN,162,0.340,0.435
47,NYM,NL,2011,718,742,77,0.335,0.391,0.264,0,NaN,NaN,162,0.332,0.411
48,NYY,AL,2011,867,657,97,0.343,0.444,0.263,1,2.0,4.0,162,0.322,0.399
49,OAK,AL,2011,645,679,74,0.311,0.369,0.244,0,NaN,NaN,162,0.317,0.378

In [21]:
test = data.iloc[:35]

In [22]:
test.head(50)

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424
5,CHW,AL,2012,748,676,85,0.318,0.422,0.255,0,NaN,NaN,162,0.319,0.405
6,CIN,NL,2012,669,588,97,0.315,0.411,0.251,1,2.0,4.0,162,0.305,0.390
7,CLE,AL,2012,667,845,68,0.324,0.381,0.251,0,NaN,NaN,162,0.336,0.430
8,COL,NL,2012,758,890,64,0.330,0.436,0.274,0,NaN,NaN,162,0.357,0.470
9,DET,AL,2012,726,670,88,0.335,0.422,0.268,1,6.0,2.0,162,0.314,0.402
10,HOU,NL,2012,583,794,55,0.302,0.371,0.236,0,NaN,NaN,162,0.337,0.427
11,KCR,AL,2012,676,746,72,0.317,0.400,0.265,0,NaN,NaN,162,0.339,0.423
12,LAA,AL,2012,767,699,89,0.332,0.433,0.274,0,NaN,NaN,162,0.310,0.403
13,LAD,NL,2012,637,597,86,0.317,0.374,0.252,0,NaN,NaN,162,0.310,0.364
14,MIA,NL,2012,609,724,69,0.308,0.382,0.244,0,NaN,NaN,162,0.327,0.399
15,MIL,NL,2012,776,733,83,0.325,0.437,0.259,0,NaN,NaN,162,0.326,0.414
16,MIN,AL,2012,701,832,66,0.325,0.390,0.260,0,NaN,NaN,162,0.333,0.442
17,NYM,NL,2012,650,709,74,0.316,0.386,0.249,0,NaN,NaN,162,0.315,0.401
18,NYY,AL,2012,804,668,95,0.337,0.453,0.265,1,3.0,3.0,162,0.311,0.419
19,OAK,AL,2012,713,614,94,0.310,0.404,0.238,1,4.0,4.0,162,0.306,0.378
20,PHI,NL,2012,684,680,81,0.317,0.400,0.255,0,NaN,NaN,162,0.306,0.407
21,PIT,NL,2012,651,674,79,0.304,0.395,0.243,0,NaN,NaN,162,0.314,0.390
22,SDP,NL,2012,651,710,76,0.319,0.380,0.247,0,NaN,NaN,162,0.319,0.398
23,SEA,AL,2012,619,651,75,0.296,0.369,0.234,0,NaN,NaN,162,0.308,0.394
24,SFG,NL,2012,718,649,94,0.327,0.397,0.269,1,4.0,1.0,162,0.313,0.393
25,STL,NL,2012,765,648,88,0.338,0.421,0.271,1,6.0,3.0,162,0.313,0.387
26,TBR,AL,2012,697,577,90,0.317,0.394,0.240,0,NaN,NaN,162,0.294,0.352
27,TEX,AL,2012,808,707,93,0.334,0.446,0.273,1,5.0,5.0,162,0.309,0.408
28,TOR,AL,2012,716,784,73,0.309,0.407,0.245,0,NaN,NaN,162,0.335,0.438
29,WSN,NL,2012,731,594,98,0.322,0.428,0.261,1,1.0,4.0,162,0.303,0.373
30,ARI,NL,2011,731,662,94,0.322,0.413,0.250,1,5.0,4.0,162,0.316,0.409
31,ATL,NL,2011,641,605,89,0.308,0.387,0.243,0,NaN,NaN,162,0.310,0.361
32,BAL,AL,2011,708,860,69,0.316,0.413,0.257,0,NaN,NaN,162,0.341,0.460
33,BOS,AL,2011,875,737,90,0.349,0.461,0.280,0,NaN,NaN,162,0.322,0.392
34,CHC,NL,2011,654,756,71,0.314,0.401,0.256,0,NaN,NaN,162,0.335,0.413