In [86]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

In [49]:
baseball_data = pd.read_csv('baseball_data.csv')

In [50]:
baseball_data.head(5)

,Season,Name,Team,G,PA,HR,R,RBI,SB,BB%,...,ISO,BABIP,AVG,OBP,SLG,OPS,wOBA,wRC+,WAR,playerid
0,2015,Bryce Harper,WSN,153,654,42,118,99,6,19.0%,...,0.319,0.369,0.330,0.460,0.649,1.109,0.461,197,9.3,11579
1,2018,Mookie Betts,BOS,136,614,32,129,80,30,13.2%,...,0.294,0.368,0.346,0.438,0.640,1.078,0.449,185,10.6,13611
2,2018,Mike Trout,LAA,140,608,39,101,79,24,20.1%,...,0.316,0.346,0.312,0.460,0.628,1.088,0.447,188,9.5,10155
3,2019,Christian Yelich,MIL,130,580,44,100,97,30,13.8%,...,0.342,0.355,0.329,0.429,0.671,1.100,0.442,174,7.3,11477
4,2017,Mike Trout,LAA,114,507,33,92,72,22,18.5%,...,0.323,0.318,0.306,0.442,0.629,1.071,0.437,180,6.4,10155

In [51]:
baseball_data = baseball_data.drop(columns=['Season', 'Team'])

In [52]:
baseball_data = baseball_data.rename(columns={'BB%':'BB', 'K%':'K', 'wRC+':'WRCplus'})

In [53]:
baseball_data.head(5)

,Name,G,PA,HR,R,RBI,SB,BB,K,ISO,BABIP,AVG,OBP,SLG,OPS,wOBA,WRCplus,WAR,playerid
0,Bryce Harper,153,654,42,118,99,6,19.0%,20.0%,0.319,0.369,0.330,0.460,0.649,1.109,0.461,197,9.3,11579
1,Mookie Betts,136,614,32,129,80,30,13.2%,14.8%,0.294,0.368,0.346,0.438,0.640,1.078,0.449,185,10.6,13611
2,Mike Trout,140,608,39,101,79,24,20.1%,20.4%,0.316,0.346,0.312,0.460,0.628,1.088,0.447,188,9.5,10155
3,Christian Yelich,130,580,44,100,97,30,13.8%,20.3%,0.342,0.355,0.329,0.429,0.671,1.100,0.442,174,7.3,11477
4,Mike Trout,114,507,33,92,72,22,18.5%,17.8%,0.323,0.318,0.306,0.442,0.629,1.071,0.437,180,6.4,10155

In [65]:
baseball_data['BB'] = baseball_data['BB'].str.replace('%', '')

In [66]:
baseball_data['K'] = baseball_data['K'].str.replace('%', '')

In [67]:
baseball_data.head(5)

,Name,G,PA,HR,R,RBI,SB,BB,K,ISO,BABIP,AVG,OBP,SLG,OPS,wOBA,WRCplus,WAR,playerid
0,Bryce Harper,153,654,42,118,99,6,19.0,20.0,0.319,0.369,0.330,0.460,0.649,1.109,0.461,197,9.3,11579
1,Mookie Betts,136,614,32,129,80,30,13.2,14.8,0.294,0.368,0.346,0.438,0.640,1.078,0.449,185,10.6,13611
2,Mike Trout,140,608,39,101,79,24,20.1,20.4,0.316,0.346,0.312,0.460,0.628,1.088,0.447,188,9.5,10155
3,Christian Yelich,130,580,44,100,97,30,13.8,20.3,0.342,0.355,0.329,0.429,0.671,1.100,0.442,174,7.3,11477
4,Mike Trout,114,507,33,92,72,22,18.5,17.8,0.323,0.318,0.306,0.442,0.629,1.071,0.437,180,6.4,10155

In [68]:
# Prediction target for model

y = baseball_data.OPS

In [69]:
baseball_data.columns

Index(['Name', 'G', 'PA', 'HR', 'R', 'RBI', 'SB', 'BB', 'K', 'ISO', 'BABIP',
       'AVG', 'OBP', 'SLG', 'OPS', 'wOBA', 'WRCplus', 'WAR', 'playerid'],
      dtype='object')

In [70]:
features = ['G', 'PA', 'HR', 'R', 'RBI', 'SB', 'BB', 'K', 'ISO', 'BABIP', 'AVG', 'OBP', 'SLG', 'OPS', 'wOBA', 'WRCplus', 'WAR']

In [71]:
# Features for model

X = baseball_data[features]

In [72]:
X.describe

<bound method NDFrame.describe of        G   PA  HR    R  RBI  SB    BB     K    ISO  BABIP    AVG    OBP  \
0    153  654  42  118   99   6  19.0  20.0  0.319  0.369  0.330  0.460
1    136  614  32  129   80  30  13.2  14.8  0.294  0.368  0.346  0.438
2    140  608  39  101   79  24  20.1  20.4  0.316  0.346  0.312  0.460
3    130  580  44  100   97  30  13.8  20.3  0.342  0.355  0.329  0.429
4    114  507  33   92   72  22  18.5  17.8  0.323  0.318  0.306  0.442
..   ...  ...  ..  ...  ...  ..   ...   ...    ...    ...    ...    ...
847  157  607  16   51   57   0   4.8  20.6  0.115  0.244  0.215  0.256
848  155  547   3   52   38   1   6.0  13.3  0.075  0.269  0.236  0.283
849  147  552   4   59   43  16   4.7  26.1  0.095  0.305  0.227  0.264
850  147  543   4   48   38   7   4.6  14.5  0.079  0.255  0.221  0.268
851  128  522  16   40   49   2   7.9  36.8  0.128  0.237  0.168  0.243

       SLG    OPS   wOBA  WRCplus   WAR
0    0.649  1.109  0.461      197   9.3
1    0.640  1.078  0.449      185  10.6
2    0.628  1.088  0.447      188   9.5
3    0.671  1.100  0.442      174   7.3
4    0.629  1.071  0.437      180   6.4
..     ...    ...    ...      ...   ...
847  0.330  0.586  0.260       65  -1.3
848  0.311  0.594  0.256       59   0.6
849  0.322  0.587  0.255       51  -1.1
850  0.300  0.568  0.254       56   1.3
851  0.296  0.539  0.239       46  -2.6

[852 rows x 17 columns]>

In [73]:
y.describe

<bound method NDFrame.describe of 0      1.109
1      1.078
2      1.088
3      1.100
4      1.071
       ...
847    0.586
848    0.594
849    0.587
850    0.568
851    0.539
Name: OPS, Length: 852, dtype: float64>

In [81]:
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=0)

In [82]:
ops_model = DecisionTreeRegressor(random_state=0)

In [83]:
ops_model.fit(train_X, train_y)

DecisionTreeRegressor(random_state=0)

In [85]:
val_predictions = ops_model.predict(val_X)

In [87]:
print(mean_absolute_error(val_y, val_predictions))

0.0015352112676056476

In [88]:
baseball_data_2021 = pd.read_csv('baseball_data_2021.csv')

In [89]:
baseball_data_2021.head(5)

,Season,Name,Team,G,PA,HR,R,RBI,SB,BB%,K%,ISO,BABIP,AVG,OBP,SLG,wOBA,wRC+,WAR,playerid
0,2021,Bryce Harper,PHI,141,599,35,101,84,13,16.7%,22.4%,0.305,0.359,0.309,0.429,0.615,0.431,170,6.5,11579
1,2021,Juan Soto,WSN,151,654,29,111,95,9,22.2%,14.2%,0.221,0.332,0.313,0.465,0.534,0.420,163,7.0,20123
2,2021,Vladimir Guerrero Jr.,TOR,161,698,48,123,111,4,12.3%,15.8%,0.290,0.313,0.311,0.401,0.601,0.419,166,6.3,19611
3,2021,Fernando Tatis Jr.,SDP,130,546,42,99,97,25,11.4%,28.0%,0.328,0.324,0.282,0.364,0.611,0.403,156,7.3,19709
4,2021,Shohei Ohtani,LAA,158,639,46,103,100,26,15.0%,29.6%,0.335,0.303,0.257,0.372,0.592,0.393,152,5.1,19755

In [90]:
baseball_data_2021 = baseball_data_2021.drop(columns=['Season', 'Team'])

In [92]:
baseball_data_2021 = baseball_data_2021.rename(columns={'BB%':'BB', 'K%':'K', 'wRC+':'wRCplus'})

In [93]:
baseball_data_2021['BB'] = baseball_data_2021['BB'].str.replace('%', '')

In [94]:
baseball_data_2021['K'] = baseball_data_2021['K'].str.replace('%', '')

In [95]:
baseball_data_2021.head(5)

,Name,G,PA,HR,R,RBI,SB,BB,K,ISO,BABIP,AVG,OBP,SLG,wOBA,wRCplus,WAR,playerid
0,Bryce Harper,141,599,35,101,84,13,16.7,22.4,0.305,0.359,0.309,0.429,0.615,0.431,170,6.5,11579
1,Juan Soto,151,654,29,111,95,9,22.2,14.2,0.221,0.332,0.313,0.465,0.534,0.420,163,7.0,20123
2,Vladimir Guerrero Jr.,161,698,48,123,111,4,12.3,15.8,0.290,0.313,0.311,0.401,0.601,0.419,166,6.3,19611
3,Fernando Tatis Jr.,130,546,42,99,97,25,11.4,28.0,0.328,0.324,0.282,0.364,0.611,0.403,156,7.3,19709
4,Shohei Ohtani,158,639,46,103,100,26,15.0,29.6,0.335,0.303,0.257,0.372,0.592,0.393,152,5.1,19755

In [96]:
baseball_data.OPS.head(5)

0    1.109
1    1.078
2    1.088
3    1.100
4    1.071
Name: OPS, dtype: float64

In [98]:
print(val_predictions)

[0.715 0.815 0.699 0.751 0.731 0.696 0.95  0.762 0.709 0.885 0.694 0.783
 0.733 0.706 0.707 0.643 0.653 0.793 0.742 0.717 0.752 0.726 0.778 0.882
 0.622 0.808 1.032 0.824 0.83  0.687 0.893 0.758 0.699 0.818 0.889 0.834
 0.899 0.813 0.939 0.763 0.696 0.922 0.704 0.699 0.72  0.8   0.762 0.652
 0.991 0.702 0.842 0.739 0.806 0.8   0.734 1.015 0.78  0.792 0.751 0.748
 0.678 0.814 0.704 0.685 0.777 0.798 0.752 0.714 0.728 0.826 0.694 0.772
 0.693 0.806 0.681 0.847 0.78  0.822 0.776 0.724 0.704 0.704 0.799 0.718
 0.774 0.73  0.779 0.815 0.811 0.737 0.755 0.803 0.685 0.859 0.815 0.772
 0.753 0.933 0.586 0.83  0.865 0.811 0.737 0.726 0.826 0.713 0.774 0.885
 0.702 0.817 0.939 0.897 0.771 0.85  0.806 0.772 0.779 1.049 0.732 0.84
 0.721 0.863 0.83  0.707 0.718 0.777 0.748 0.746 0.929 0.808 0.916 0.742
 0.86  0.832 0.632 0.648 1.1   0.768 0.84  0.86  0.64  0.835 0.86  0.877
 0.811 0.735 0.803 0.873 0.733 0.79  0.73  0.846 0.758 0.846 0.664 0.765
 0.935 0.711 0.86  0.85  0.717 0.957 0.817 0.568 1.    0.855 0.871 0.738
 0.729 0.928 0.654 0.701 0.699 0.885 0.752 0.86  0.774 0.808 0.794 0.985
 0.752 0.938 0.798 0.736 0.721 0.825 0.751 0.795 0.725 1.049 0.617 0.83
 0.832 0.701 0.824 0.87  0.648 0.664 0.776 0.634 0.771 0.678 0.632 0.818
 0.79  0.755 0.822 0.929 0.95  0.792 0.709 0.871 0.885]

In [99]:
def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

In [100]:
for max_leaf_nodes in [5, 50, 500, 5000]:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, my_mae))

Max leaf nodes: 5  		 Mean Absolute Error:  0
Max leaf nodes: 50  		 Mean Absolute Error:  0
Max leaf nodes: 500  		 Mean Absolute Error:  0
Max leaf nodes: 5000  		 Mean Absolute Error:  0